/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chap10IG1;

import javax.swing.JOptionPane;

/**
 *
 * @author stagiaire
 */
public class JFFTest extends javax.swing.JFrame {

    /**
     * Creates new form JFFTest
     */
    public JFFTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFPrenom = new javax.swing.JTextField();
        JBTValider = new javax.swing.JButton();
        JLBonjour = new javax.swing.JLabel();
        JBTQuitter = new javax.swing.JButton();
        JBTSuite = new javax.swing.JButton();
        JLFond = new javax.swing.JLabel();
        JFLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identification");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Votre prénom: ");

        JTFPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPrenomActionPerformed(evt);
            }
        });

        JBTValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap10IG1/img/valider.png"))); // NOI18N
        JBTValider.setText("Valider");
        JBTValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTValiderActionPerformed(evt);
            }
        });

        JLBonjour.setText("Bonjour !!!");

        JBTQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap10IG1/img/quitter.png"))); // NOI18N
        JBTQuitter.setText("Quitter");
        JBTQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTQuitterActionPerformed(evt);
            }
        });

        JBTSuite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap10IG1/img/suite.png"))); // NOI18N
        JBTSuite.setText("Suite");
        JBTSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTSuiteActionPerformed(evt);
            }
        });

        JLFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap10IG1/img/fondClair.png"))); // NOI18N

        JFLabel.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        JFLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap10IG1/img/utilisateur.png"))); // NOI18N
        JFLabel.setText("Qui êtes-vous?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(JFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(JTFPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(JBTValider, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(JLBonjour, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(JBTQuitter)
                        .addGap(53, 53, 53)
                        .addComponent(JBTSuite))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JLFond)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(JTFPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(JBTValider, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(JLBonjour, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JLFond, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBTQuitter)
                    .addComponent(JBTSuite)))
        );

        setBounds(0, 0, 508, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void JTFPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPrenomActionPerformed
        String prenom = JTFPrenom.getText();
        JLBonjour.setText("Bonjour  " + prenom + "  !!!");
    }//GEN-LAST:event_JTFPrenomActionPerformed

    private void JBTValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTValiderActionPerformed
        String prenom = JTFPrenom.getText();
        JLBonjour.setText("Bonjour  " + prenom + "  !!!");
    }//GEN-LAST:event_JBTValiderActionPerformed

    private void JBTQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBTQuitterActionPerformed

    private void JBTSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTSuiteActionPerformed
        JOptionPane.showMessageDialog(null, "Patience... La suite est en cours de réalisation ");
    }//GEN-LAST:event_JBTSuiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTQuitter;
    private javax.swing.JButton JBTSuite;
    private javax.swing.JButton JBTValider;
    private javax.swing.JLabel JFLabel;
    private javax.swing.JLabel JLBonjour;
    private javax.swing.JLabel JLFond;
    private javax.swing.JTextField JTFPrenom;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
